### ISSUE TITLE
Help needed for hedgehog/QuickCheck test

### ISSUE THREAD

**Issue by jonathanjouty** [scrive/hpqtypes#14]
@arybczak maybe you can help me with this, since I know very little of this library...

What I want to do is create a test for `ToSQL` -> `FromSQL` roundtrip, using `hedgehog` or QuickCheck as the generator, and thus validate that the instances are properly defined.

So far all I have is this (using `Gen` from `hedgehog`):
```hs
import Database.PostgreSQL.PQTypes
import Hedgehog
import Foreign.Ptr (Ptr)
-- Does not type-check with annotation :/
-- Even though I took the types GHC told me to...
-- Type-checks without it though!
--toSQLFromSQLRoundtrip
--  :: ( MonadIO m, Show a, Eq a, ToSQL a, FromSQL a
--     , PQDest a ~ PQDest t)
--  => Gen a
--  -> PropertyT m ()
toSQLFromSQLRoundtrip gen = do
  a  <- forAll gen
  r  <- liftIO $ toSQL a paramAllocater ptrPutter
  a' <- liftIO $ fromSQL (Just r)
  a === a'

paramAllocater :: ParamAllocator
paramAllocater = undefined -- TODO

ptrPutter :: Ptr (PQDest t) -> IO r
ptrPutter = undefined -- TODO
```

Basically I've not gotten very far, and I have no idea where to start with the rest :)

**Comment by arybczak** [comment]
The general idea is sound. The code doesn't type check with a signature because `t` is ambiguous. I think you want `PQDest a ~ PQBase a`.

**Comment by jonathanjouty** [comment]
Right—I'll try that.

My main question was about what to do with these though:
```hs
paramAllocater :: ParamAllocator
paramAllocater = undefined -- TODO

ptrPutter :: Ptr (PQDest t) -> IO r
ptrPutter = undefined -- TODO
```

Is there a way to construct some reasonable versions for tests?

**Comment by jonathanjouty** [comment]
With @arybczak's help I ended implementing the following, which can be used quite easily to create a _hedgehog_ `Property`:
```hs
{-# LANGUAGE OverloadedStrings #-}
module Database.PostgreSQL.PQTypes.Extra.Test
( toSQLFromSQLRoundtrip
) where

import Database.PostgreSQL.PQTypes
import Control.Monad.Catch (MonadThrow)
import Hedgehog

toSQLFromSQLRoundtrip
  :: (MonadDB m, MonadThrow m, Show a, Eq a, ToSQL a, FromSQL a)
  => (m a -> IO a)
  -> Gen a
  -> Property
toSQLFromSQLRoundtrip runDB gen = property $ do
  a <- forAll gen
  r <- lift $ runDB $ do
    runSQL_ $ "SELECT" <?> a
    fetchOne runIdentity
  a === r
```

This mimics the existing tests for `hpqtypes`:
https://github.com/scrive/hpqtypes/blob/master/test/Main.hs#L411-L422
