### ISSUE TITLE
Comparison to libpq

### ISSUE THREAD

**Issue by hughjfchen** [scrive/hpqtypes#16]
What's the difference between this and the libpq. I heard the libpq has some thread problem. Does this one also suffer from the same problem?

**Comment by jonathanjouty** [comment]
> I heard the libpq has some thread problem.

@hughjfchen do you have a specific source or issue tracker link to the said problem?
Without that, it is hearsay, and basically impossible to identify if this library also suffers from this unidentified problem.

> Does this one also suffer from the same problem?

We have been using this library in production without any issues.

**Comment by hughjfchen** [comment]
Sorry I mixed the libpq with the mysql binding. Here is the link to the mysql binding concurrent problem. [mysql binding concurrent problem](https://ro-che.info/articles/2015-04-17-safe-concurrent-mysql-haskell). Does this binding has the same concurrent problem?

**Comment by 23Skidoo** [comment]
Most of the issues there seem MySQL-specific, except the first one (unsafe calls).

**Comment by hughjfchen** [comment]
> Most of the issues listed in that article seem `libmysqlclient`-specific, except the first one (unsafe calls).

Yes, the first one is what I'm talking about.

**Comment by arybczak** [comment]
> Does this binding has the same concurrent problem?

No.
