### ISSUE TITLE
Doesn't support GHC 7.6 and 7.4

### ISSUE THREAD

**Issue by 23Skidoo** [scrive/hpqtypes#3]
Closed type families are not supported by GHC 7.6, so when trying to compile with 7.6 I get:

```
src/Database/PostgreSQL/PQTypes/Internal/Utils.hs:38:32:
    parse error on input `where'
```

And the constraint on `base` prevents building on 7.4 (see #2). Probably wontfix, so the ticket is just for the record.

**Comment by 23Skidoo** [comment]
Confirmed wontfix after taliking to @jonathanjouty.

**Comment by arybczak** [comment]
For the record, closed type families are not needed for MkConstraint to work, so in principle this could be made to work.

**Comment by 23Skidoo** [comment]
Patches welcome!
